/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientProprietesRouteImport } from './routes/client.proprietes'
import { Route as ClientDocumentsRouteImport } from './routes/client.documents'
import { Route as ClientChronologieRouteImport } from './routes/client.chronologie'
import { Route as ClientAssistantRouteImport } from './routes/client.assistant'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProprietesRoute = ClientProprietesRouteImport.update({
  id: '/proprietes',
  path: '/proprietes',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const ClientChronologieRoute = ClientChronologieRouteImport.update({
  id: '/chronologie',
  path: '/chronologie',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAssistantRoute = ClientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/chronologie': typeof ClientChronologieRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/proprietes': typeof ClientProprietesRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/chronologie': typeof ClientChronologieRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/proprietes': typeof ClientProprietesRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/chronologie': typeof ClientChronologieRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/proprietes': typeof ClientProprietesRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/login'
    | '/client/assistant'
    | '/client/chronologie'
    | '/client/documents'
    | '/client/proprietes'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/client/assistant'
    | '/client/chronologie'
    | '/client/documents'
    | '/client/proprietes'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/login'
    | '/client/assistant'
    | '/client/chronologie'
    | '/client/documents'
    | '/client/proprietes'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/proprietes': {
      id: '/client/proprietes'
      path: '/proprietes'
      fullPath: '/client/proprietes'
      preLoaderRoute: typeof ClientProprietesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/chronologie': {
      id: '/client/chronologie'
      path: '/chronologie'
      fullPath: '/client/chronologie'
      preLoaderRoute: typeof ClientChronologieRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/assistant': {
      id: '/client/assistant'
      path: '/assistant'
      fullPath: '/client/assistant'
      preLoaderRoute: typeof ClientAssistantRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientAssistantRoute: typeof ClientAssistantRoute
  ClientChronologieRoute: typeof ClientChronologieRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientProprietesRoute: typeof ClientProprietesRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAssistantRoute: ClientAssistantRoute,
  ClientChronologieRoute: ClientChronologieRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientProprietesRoute: ClientProprietesRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
