/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AgentRechercheRouteImport } from './routes/agent.recherche'
import { Route as AgentProfileRouteImport } from './routes/agent.profile'
import { Route as AgentDossiersRouteImport } from './routes/agent.dossiers'
import { Route as AgentDossierRouteImport } from './routes/agent.dossier'
import { Route as AgentClientsRouteImport } from './routes/agent.clients'
import { Route as AgentAgendaRouteImport } from './routes/agent.agenda'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminDossierRouteImport } from './routes/admin.dossier'
import { Route as AdminAutomationsRouteImport } from './routes/admin.automations'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AgentDossiersIndexRouteImport } from './routes/agent.dossiers.index'
import { Route as AgentDossiersCreateRouteImport } from './routes/agent.dossiers.create'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AgentRechercheRoute = AgentRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDossiersRoute = AgentDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDossierRoute = AgentDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AgentRoute,
} as any)
const AgentClientsRoute = AgentClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgendaRoute = AgentAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AgentRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDossierRoute = AdminDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationsRoute = AdminAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AgentDossiersIndexRoute = AgentDossiersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentDossiersRoute,
} as any)
const AgentDossiersCreateRoute = AgentDossiersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AgentDossiersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/dossier': typeof AdminDossierRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/profile': typeof AdminProfileRoute
  '/agent/agenda': typeof AgentAgendaRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/dossier': typeof AgentDossierRoute
  '/agent/dossiers': typeof AgentDossiersRouteWithChildren
  '/agent/profile': typeof AgentProfileRoute
  '/agent/recherche': typeof AgentRechercheRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/dossiers/create': typeof AgentDossiersCreateRoute
  '/agent/dossiers/': typeof AgentDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/dossier': typeof AdminDossierRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/profile': typeof AdminProfileRoute
  '/agent/agenda': typeof AgentAgendaRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/dossier': typeof AgentDossierRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/recherche': typeof AgentRechercheRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/agent/dossiers/create': typeof AgentDossiersCreateRoute
  '/agent/dossiers': typeof AgentDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/dossier': typeof AdminDossierRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/profile': typeof AdminProfileRoute
  '/agent/agenda': typeof AgentAgendaRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/dossier': typeof AgentDossierRoute
  '/agent/dossiers': typeof AgentDossiersRouteWithChildren
  '/agent/profile': typeof AgentProfileRoute
  '/agent/recherche': typeof AgentRechercheRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/dossiers/create': typeof AgentDossiersCreateRoute
  '/agent/dossiers/': typeof AgentDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/design-system'
    | '/login'
    | '/reset-password'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/automations'
    | '/admin/dossier'
    | '/admin/pipeline'
    | '/admin/profile'
    | '/agent/agenda'
    | '/agent/clients'
    | '/agent/dossier'
    | '/agent/dossiers'
    | '/agent/profile'
    | '/agent/recherche'
    | '/admin/'
    | '/agent/'
    | '/agent/dossiers/create'
    | '/agent/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/reset-password'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/automations'
    | '/admin/dossier'
    | '/admin/pipeline'
    | '/admin/profile'
    | '/agent/agenda'
    | '/agent/clients'
    | '/agent/dossier'
    | '/agent/profile'
    | '/agent/recherche'
    | '/admin'
    | '/agent'
    | '/agent/dossiers/create'
    | '/agent/dossiers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/design-system'
    | '/login'
    | '/reset-password'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/automations'
    | '/admin/dossier'
    | '/admin/pipeline'
    | '/admin/profile'
    | '/agent/agenda'
    | '/agent/clients'
    | '/agent/dossier'
    | '/agent/dossiers'
    | '/agent/profile'
    | '/agent/recherche'
    | '/admin/'
    | '/agent/'
    | '/agent/dossiers/create'
    | '/agent/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/recherche': {
      id: '/agent/recherche'
      path: '/recherche'
      fullPath: '/agent/recherche'
      preLoaderRoute: typeof AgentRechercheRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/dossiers': {
      id: '/agent/dossiers'
      path: '/dossiers'
      fullPath: '/agent/dossiers'
      preLoaderRoute: typeof AgentDossiersRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/dossier': {
      id: '/agent/dossier'
      path: '/dossier'
      fullPath: '/agent/dossier'
      preLoaderRoute: typeof AgentDossierRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/clients': {
      id: '/agent/clients'
      path: '/clients'
      fullPath: '/agent/clients'
      preLoaderRoute: typeof AgentClientsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agenda': {
      id: '/agent/agenda'
      path: '/agenda'
      fullPath: '/agent/agenda'
      preLoaderRoute: typeof AgentAgendaRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dossier': {
      id: '/admin/dossier'
      path: '/dossier'
      fullPath: '/admin/dossier'
      preLoaderRoute: typeof AdminDossierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automations': {
      id: '/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AdminAutomationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/dossiers/': {
      id: '/agent/dossiers/'
      path: '/'
      fullPath: '/agent/dossiers/'
      preLoaderRoute: typeof AgentDossiersIndexRouteImport
      parentRoute: typeof AgentDossiersRoute
    }
    '/agent/dossiers/create': {
      id: '/agent/dossiers/create'
      path: '/create'
      fullPath: '/agent/dossiers/create'
      preLoaderRoute: typeof AgentDossiersCreateRouteImport
      parentRoute: typeof AgentDossiersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAutomationsRoute: typeof AdminAutomationsRoute
  AdminDossierRoute: typeof AdminDossierRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAutomationsRoute: AdminAutomationsRoute,
  AdminDossierRoute: AdminDossierRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentDossiersRouteChildren {
  AgentDossiersCreateRoute: typeof AgentDossiersCreateRoute
  AgentDossiersIndexRoute: typeof AgentDossiersIndexRoute
}

const AgentDossiersRouteChildren: AgentDossiersRouteChildren = {
  AgentDossiersCreateRoute: AgentDossiersCreateRoute,
  AgentDossiersIndexRoute: AgentDossiersIndexRoute,
}

const AgentDossiersRouteWithChildren = AgentDossiersRoute._addFileChildren(
  AgentDossiersRouteChildren,
)

interface AgentRouteChildren {
  AgentAgendaRoute: typeof AgentAgendaRoute
  AgentClientsRoute: typeof AgentClientsRoute
  AgentDossierRoute: typeof AgentDossierRoute
  AgentDossiersRoute: typeof AgentDossiersRouteWithChildren
  AgentProfileRoute: typeof AgentProfileRoute
  AgentRechercheRoute: typeof AgentRechercheRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAgendaRoute: AgentAgendaRoute,
  AgentClientsRoute: AgentClientsRoute,
  AgentDossierRoute: AgentDossierRoute,
  AgentDossiersRoute: AgentDossiersRouteWithChildren,
  AgentProfileRoute: AgentProfileRoute,
  AgentRechercheRoute: AgentRechercheRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
